// ============================================================================
// LeetCode 热题 100 题单配置
// Top 100 Liked Questions 清单 + 完成进度
// done: 是否已刷（依据 E:\LeetCode-Solutions 本机题解库真实记录）
// ============================================================================

export interface Hot100Item {
	num: number;
	title: string;
	en: string;
	done: boolean;
	scene?: string;
	blogSlug?: string;
}

// 本机题解库已做题号（E:\LeetCode-Solutions，64 道唯一题：1-60 + 128/239/283/438/560）
const SOLVED = new Set<number>([
	1, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
	23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41,
	42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
	128, 239, 283, 438, 560,
]);

// 热题 100 题单（常见版本，可能与官方略有出入；◆ 为中国站候选题）
// 每题的 scene 为游戏情境设计（已有场景标注的来自本机题解注释）
const items: Array<Omit<Hot100Item, "done">> = [
	{
		num: 1,
		title: "两数之和",
		en: "Two Sum",
		scene: "背包合成：两材料等级之和=目标值",
		blogSlug: "leetcode-two-sum",
	},
	{
		num: 2,
		title: "两数相加",
		en: "Add Two Numbers",
		scene: "经验值相加：模拟进位",
	},
	{
		num: 3,
		title: "无重复字符的最长子串",
		en: "Longest Substring Without Repeating Characters",
		scene: "技能CD：最长无重复连招窗口",
		blogSlug: "leetcode-longest-substring",
	},
	{
		num: 4,
		title: "寻找两个正序数组的中位数",
		en: "Median of Two Sorted Arrays",
		scene: "排行榜合并取中位",
	},
	{
		num: 5,
		title: "最长回文子串",
		en: "Longest Palindromic Substring",
		scene: "角色名回文检查",
	},
	{
		num: 10,
		title: "正则表达式匹配",
		en: "Regular Expression Matching",
		scene: "作弊检测通配符匹配",
	},
	{
		num: 11,
		title: "盛最多水的容器",
		en: "Container With Most Water",
		scene: "战斗边界：容器容量",
		blogSlug: "leetcode-container-with-most-water",
	},
	{
		num: 15,
		title: "三数之和",
		en: "3Sum",
		scene: "技能组合：三技能凑阈值",
		blogSlug: "leetcode-3sum",
	},
	{
		num: 17,
		title: "电话号码的字母组合",
		en: "Letter Combinations of a Phone Number",
		scene: "连招表：按键组合枚举",
	},
	{
		num: 19,
		title: "删除链表的倒数第 N 个结点",
		en: "Remove Nth Node From End of List",
		scene: "血条列表移除",
	},
	{
		num: 20,
		title: "有效的括号",
		en: "Valid Parentheses",
		scene: "技能括号配对合法性",
		blogSlug: "leetcode-valid-parentheses",
	},
	{
		num: 21,
		title: "合并两个有序链表",
		en: "Merge Two Sorted Lists",
		scene: "掉落物排序合并",
		blogSlug: "leetcode-merge-two-lists",
	},
	{
		num: 22,
		title: "括号生成",
		en: "Generate Parentheses",
		scene: "连招括号生成",
	},
	{
		num: 23,
		title: "合并 K 个升序链表",
		en: "Merge k Sorted Lists",
		scene: "多副本掉落汇总",
	},
	{
		num: 24,
		title: "两两交换链表中的节点",
		en: "Swap Nodes in Pairs",
		scene: "对局轮换",
	},
	{
		num: 25,
		title: "K 个一组翻转链表",
		en: "Reverse Nodes in k-Group",
		scene: "回合制战斗分组",
	},
	{
		num: 31,
		title: "下一个排列",
		en: "Next Permutation",
		scene: "装备方案下一种",
	},
	{
		num: 32,
		title: "最长有效括号",
		en: "Longest Valid Parentheses",
		scene: "连招有效窗口",
	},
	{
		num: 33,
		title: "搜索旋转排序数组",
		en: "Search in Rotated Sorted Array",
		scene: "地图传送点检索",
	},
	{
		num: 34,
		title: "在排序数组中查找元素的第一个和最后一个位置",
		en: "Find First and Last Position",
		scene: "掉落物区间查询",
	},
	{
		num: 35,
		title: "搜索插入位置",
		en: "Search Insert Position",
		scene: "排行榜插入位",
	},
	{ num: 39, title: "组合总和", en: "Combination Sum", scene: "材料配方组合" },
	{
		num: 41,
		title: "缺失的第一个正数",
		en: "First Missing Positive",
		scene: "成就编号补缺",
	},
	{ num: 42, title: "接雨水", en: "Trapping Rain Water", scene: "地形积水" },
	{ num: 45, title: "跳跃游戏 II", en: "Jump Game II", scene: "关卡最少跳跃" },
	{ num: 46, title: "全排列", en: "Permutations", scene: "技能顺序排列" },
	{ num: 48, title: "旋转图像", en: "Rotate Image", scene: "地图旋转" },
	{
		num: 49,
		title: "字母异位词分组",
		en: "Group Anagrams",
		scene: "技能资源分类",
		blogSlug: "leetcode-group-anagrams",
	},
	{ num: 51, title: "N 皇后", en: "N-Queens", scene: "棋盘布防" },
	{
		num: 53,
		title: "最大子数组和",
		en: "Maximum Subarray",
		scene: "DPS 峰值窗口",
		blogSlug: "leetcode-maximum-subarray",
	},
	{ num: 54, title: "螺旋矩阵", en: "Spiral Matrix", scene: "迷宫探索路径" },
	{ num: 55, title: "跳跃游戏", en: "Jump Game", scene: "关卡可达性" },
	{
		num: 56,
		title: "合并区间",
		en: "Merge Intervals",
		scene: "Buff 时间段合并",
	},
	{ num: 62, title: "不同路径", en: "Unique Paths", scene: "棋盘走法数" },
	{
		num: 64,
		title: "最小路径和",
		en: "Minimum Path Sum",
		scene: "地图最优路线",
	},
	{ num: 70, title: "爬楼梯", en: "Climbing Stairs", scene: "等级升级方式数" },
	{ num: 72, title: "编辑距离", en: "Edit Distance", scene: "技能名纠错" },
	{
		num: 73,
		title: "矩阵置零",
		en: "Set Matrix Zeroes",
		scene: "机关联动清零",
	},
	{
		num: 74,
		title: "搜索二维矩阵",
		en: "Search a 2D Matrix",
		scene: "地图坐标检索",
	},
	{ num: 75, title: "颜色分类", en: "Sort Colors", scene: "装备品质排序" },
	{
		num: 76,
		title: "最小覆盖子串",
		en: "Minimum Window Substring",
		scene: "材料集齐最短刷本",
	},
	{ num: 78, title: "子集", en: "Subsets", scene: "天赋组合枚举" },
	{ num: 79, title: "单词搜索", en: "Word Search", scene: "藏宝图路径" },
	{
		num: 84,
		title: "柱状图中最大的矩形",
		en: "Largest Rectangle in Histogram",
		scene: "建造面积最大化",
	},
	{ num: 85, title: "最大矩形", en: "Maximal Rectangle", scene: "领地规划" },
	{
		num: 94,
		title: "二叉树的中序遍历",
		en: "Binary Tree Inorder Traversal",
		scene: "技能树遍历",
	},
	{
		num: 96,
		title: "不同的二叉搜索树",
		en: "Unique Binary Search Trees",
		scene: "装备树结构数",
	},
	{
		num: 98,
		title: "验证二叉搜索树",
		en: "Validate Binary Search Tree",
		scene: "属性树合法性",
	},
	{
		num: 101,
		title: "对称二叉树",
		en: "Symmetric Tree",
		scene: "镜像场景检查",
	},
	{
		num: 102,
		title: "二叉树的层序遍历",
		en: "Binary Tree Level Order Traversal",
		scene: "技能树层级解锁",
	},
	{
		num: 104,
		title: "二叉树的最大深度",
		en: "Maximum Depth of Binary Tree",
		scene: "技能树深度",
	},
	{
		num: 105,
		title: "从前序与中序遍历序列构造二叉树",
		en: "Construct Binary Tree",
		scene: "场景树重建",
	},
	{
		num: 108,
		title: "将有序数组转换为二叉搜索树",
		en: "Convert Sorted Array to BST",
		scene: "技能树平衡化",
	},
	{
		num: 114,
		title: "二叉树展开为链表",
		en: "Flatten Binary Tree to Linked List",
		scene: "技能链展开",
	},
	{
		num: 118,
		title: "杨辉三角",
		en: "Pascal's Triangle",
		scene: "经验分配层数",
	},
	{
		num: 121,
		title: "买卖股票的最佳时机",
		en: "Best Time to Buy and Sell Stock",
		scene: "交易行低买高卖",
	},
	{
		num: 124,
		title: "二叉树中的最大路径和",
		en: "Binary Tree Maximum Path Sum",
		scene: "装备属性路径",
	},
	{
		num: 128,
		title: "最长连续序列",
		en: "Longest Consecutive Sequence",
		scene: "任务链：最长连续关卡",
		blogSlug: "leetcode-longest-consecutive",
	},
	{
		num: 131,
		title: "分割回文串",
		en: "Palindrome Partitioning",
		scene: "名字拆分",
	},
	{ num: 134, title: "加油站", en: "Gas Station", scene: "补给站循环" },
	{ num: 135, title: "分发糖果", en: "Candy", scene: "奖励分配" },
	{
		num: 136,
		title: "只出现一次的数字",
		en: "Single Number",
		scene: "异或找唯一掉落",
	},
	{
		num: 138,
		title: "随机链表的复制",
		en: "Copy List with Random Pointer",
		scene: "存档深拷贝",
	},
	{ num: 139, title: "单词拆分", en: "Word Break", scene: "输入指令拆分" },
	{ num: 141, title: "环形链表", en: "Linked List Cycle", scene: "地图环检测" },
	{
		num: 142,
		title: "环形链表 II",
		en: "Linked List Cycle II",
		scene: "环路入口",
	},
	{ num: 146, title: "LRU 缓存", en: "LRU Cache", scene: "最近使用装备缓存" },
	{ num: 148, title: "排序链表", en: "Sort List", scene: "掉落排序" },
	{
		num: 152,
		title: "乘积最大子数组",
		en: "Maximum Product Subarray",
		scene: "Buff 叠乘最大化",
	},
	{
		num: 153,
		title: "寻找旋转排序数组中的最小值",
		en: "Find Minimum in Rotated Sorted Array",
		scene: "地图最低点",
	},
	{ num: 155, title: "最小栈", en: "Min Stack", scene: "背包最小值追踪" },
	{
		num: 160,
		title: "相交链表",
		en: "Intersection of Two Linked Lists",
		scene: "任务线交汇",
	},
	{ num: 169, title: "多数元素", en: "Majority Element", scene: "投票占多数" },
	{ num: 189, title: "轮转数组", en: "Rotate Array", scene: "轮换队伍" },
	{ num: 198, title: "打家劫舍", en: "House Robber", scene: "宝箱取舍" },
	{
		num: 199,
		title: "二叉树的右视图",
		en: "Binary Tree Right Side View",
		scene: "技能树右视图",
	},
	{
		num: 200,
		title: "岛屿数量",
		en: "Number of Islands",
		scene: "地图岛屿统计",
	},
	{
		num: 206,
		title: "反转链表",
		en: "Reverse Linked List",
		scene: "任务线反转",
	},
	{ num: 207, title: "课程表", en: "Course Schedule", scene: "技能前置学习" },
	{
		num: 208,
		title: "实现 Trie（前缀树）",
		en: "Implement Trie",
		scene: "技能名自动补全",
	},
	{
		num: 215,
		title: "数组中的第 K 个最大元素",
		en: "Kth Largest Element",
		scene: "排行榜第K名",
	},
	{
		num: 221,
		title: "最大正方形",
		en: "Maximal Square",
		scene: "基地最大方形",
	},
	{
		num: 226,
		title: "翻转二叉树",
		en: "Invert Binary Tree",
		scene: "镜像世界",
	},
	{
		num: 230,
		title: "二叉搜索树中第 K 小的元素",
		en: "Kth Smallest Element in a BST",
		scene: "属性阈值查询",
	},
	{
		num: 234,
		title: "回文链表",
		en: "Palindrome Linked List",
		scene: "对称任务链",
	},
	{
		num: 236,
		title: "二叉树的最近公共祖先",
		en: "Lowest Common Ancestor",
		scene: "技能树共同前置",
	},
	{
		num: 238,
		title: "除自身以外数组的乘积",
		en: "Product of Array Except Self",
		scene: "装备加成互斥",
	},
	{
		num: 239,
		title: "滑动窗口最大值",
		en: "Sliding Window Maximum",
		scene: "战斗伤害峰值",
	},
	{
		num: 240,
		title: "搜索二维矩阵 II",
		en: "Search a 2D Matrix II",
		scene: "地图右上检索",
	},
	{ num: 253, title: "会议室 II", en: "Meeting Rooms II", scene: "副本并发" },
	{
		num: 279,
		title: "完全平方数",
		en: "Perfect Squares",
		scene: "方块合成最少",
	},
	{
		num: 283,
		title: "移动零",
		en: "Move Zeroes",
		scene: "背包零元素归位",
		blogSlug: "leetcode-move-zeroes",
	},
	{
		num: 287,
		title: "寻找重复数",
		en: "Find the Duplicate Number",
		scene: "重复掉落检测",
	},
	{
		num: 295,
		title: "数据流的中位数",
		en: "Find Median from Data Stream",
		scene: "实时中位属性",
	},
	{
		num: 297,
		title: "二叉树的序列化与反序列化",
		en: "Serialize and Deserialize Binary Tree",
		scene: "技能树存档",
	},
	{
		num: 300,
		title: "最长递增子序列",
		en: "Longest Increasing Subsequence",
		scene: "成长曲线",
	},
	{
		num: 301,
		title: "删除无效的括号",
		en: "Remove Invalid Parentheses",
		scene: "指令净化",
	},
	{
		num: 309,
		title: "最佳买卖股票时机含冷冻期",
		en: "Best Time to Buy and Sell Stock with Cooldown",
		scene: "交易CD限制",
	},
	{ num: 312, title: "戳气球", en: "Burst Balloons", scene: "气球连消" },
	{ num: 322, title: "零钱兑换", en: "Coin Change", scene: "金币最少换法" },
	{
		num: 337,
		title: "打家劫舍 III",
		en: "House Robber III",
		scene: "树形宝箱",
	},
	{ num: 338, title: "比特位计数", en: "Counting Bits", scene: "技能点二进制" },
	{
		num: 347,
		title: "前 K 个高频元素",
		en: "Top K Frequent Elements",
		scene: "热门掉落TopK",
	},
	{ num: 394, title: "字符串解码", en: "Decode String", scene: "压缩指令解压" },
	{
		num: 399,
		title: "除法求值",
		en: "Evaluate Division",
		scene: "合成倍率换算",
	},
	{
		num: 406,
		title: "根据身高重建队列",
		en: "Queue Reconstruction by Height",
		scene: "角色站位重建",
	},
	{
		num: 416,
		title: "分割等和子集",
		en: "Partition Equal Subset Sum",
		scene: "物品平分",
	},
	{
		num: 437,
		title: "路径总和 III",
		en: "Path Sum III",
		scene: "路线收益计数",
	},
	{
		num: 438,
		title: "找到字符串中所有字母异位词",
		en: "Find All Anagrams in a String",
		scene: "技能资源分类",
	},
	{
		num: 448,
		title: "找到所有数组中消失的数字",
		en: "Find All Numbers Disappeared",
		scene: "缺失成就检测",
	},
	{
		num: 461,
		title: "汉明距离",
		en: "Hamming Distance",
		scene: "存档差异对比",
	},
	{ num: 494, title: "目标和", en: "Target Sum", scene: "技能正负加成" },
	{
		num: 538,
		title: "把二叉搜索树转换为累加树",
		en: "Convert BST to Greater Tree",
		scene: "属性累加树",
	},
	{
		num: 543,
		title: "二叉树的直径",
		en: "Diameter of Binary Tree",
		scene: "技能树最长路径",
	},
	{
		num: 560,
		title: "和为 K 的子数组",
		en: "Subarray Sum Equals K",
		scene: "金币凑数",
	},
	{
		num: 581,
		title: "最短无序连续子数组",
		en: "Shortest Unsorted Continuous Subarray",
		scene: "乱序装备段",
	},
	{
		num: 617,
		title: "合并二叉树",
		en: "Merge Two Binary Trees",
		scene: "双技能树融合",
	},
	{ num: 621, title: "任务调度器", en: "Task Scheduler", scene: "CD任务调度" },
	{
		num: 647,
		title: "回文子串",
		en: "Palindromic Substrings",
		scene: "名字回文计数",
	},
	{
		num: 739,
		title: "每日温度",
		en: "Daily Temperatures",
		scene: "温度变化预测",
	},
	{
		num: 763,
		title: "划分字母区间",
		en: "Partition Labels",
		scene: "区域划分",
	},
	{
		num: 994,
		title: "腐烂的橘子",
		en: "Rotting Oranges",
		scene: "感染扩散BFS",
	},
	{
		num: 1143,
		title: "最长公共子序列",
		en: "Longest Common Subsequence",
		scene: "技能连招相似度",
	},
];

export const hot100List: Hot100Item[] = items.map((i) => ({
	...i,
	done: SOLVED.has(i.num),
}));

export const hot100Stats = {
	total: hot100List.length,
	done: hot100List.filter((i) => i.done).length,
	published: hot100List.filter((i) => i.blogSlug).length,
};
