// ============================================================================
// 面试题库配置 - 游戏客户端开发（C++ / 图形学 / UE / 算法 / 计算机基础）
// Interview Question Bank Configuration
// 修改此文件即可更新博客上的面试题库页面
// ============================================================================
import type { InterviewConfig } from "../types/interview";

export const interviewConfig: InterviewConfig = {
	title: "游戏客户端面试题库",
	description:
		"围绕游戏客户端实习面试高频考点整理的题库，涵盖 C++、图形学、Unreal 引擎、算法与计算机基础。点击题目展开参考答案要点。",

	categories: [
		{
			id: "cpp",
			name: "C++",
			description: "游戏客户端第一语言，几乎每场面试必考",
			icon: "material-symbols:data-object",
			questions: [
				{
					id: "cpp-01",
					question: "谈谈虚函数的工作原理（vtable / vptr）",
					hint: "多态的实现机制，构造/析构中的虚函数行为",
					answer: [
						"每个含虚函数的类有一个虚函数表（vtable），存放虚函数指针",
						"对象内存中隐藏一个虚表指针（vptr），构造时指向所属类的 vtable",
						"调用虚函数时通过 vptr → vtable → 函数指针间接调用，实现运行时多态",
						"多重继承下对象有多个 vptr；虚继承还有虚基类表",
						"构造函数中虚函数不触发动态绑定（对象尚未完成构造）；析构同理",
					],
					difficulty: "medium",
					tags: ["多态", "内存布局"],
				},
				{
					id: "cpp-02",
					question: "智能指针的原理与区别：unique_ptr / shared_ptr / weak_ptr",
					hint: "RAII、引用计数、循环引用",
					answer: [
						"unique_ptr：独占所有权，不可拷贝，可移动，RAII 自动释放",
						"shared_ptr：引用计数共享所有权，计数归零时释放；线程安全只保证计数本身",
						"weak_ptr：不增加引用计数，用于打破循环引用，需 lock() 提升为 shared_ptr",
						"循环引用示例：两个对象互相持有 shared_ptr 导致内存泄漏，用 weak_ptr 解决",
						"面试加分：控制块（control block）概念、make_shared 的性能优势（一次分配）",
					],
					difficulty: "medium",
					tags: ["内存", "RAII"],
				},
				{
					id: "cpp-03",
					question: "左值右值、移动语义与完美转发",
					hint: "C++11 核心特性，游戏引擎高频使用",
					answer: [
						"左值有持久地址，右值是临时对象（字面量、表达式结果）",
						"右值引用 T&& 绑定右值，std::move 将左值转为右值以触发移动语义",
						"移动构造/移动赋值：转移资源所有权而非深拷贝，性能关键",
						"完美转发：模板参数 T&& + std::forward<T> 保持参数原始左/右值属性",
						"游戏场景：vector 扩容、字符串拼接、资源句柄传递",
					],
					difficulty: "hard",
					tags: ["C++11", "性能"],
				},
				{
					id: "cpp-04",
					question: "const 的多种用法（顶层/底层 const）",
					hint: "const 修饰对象、指针、成员函数",
					answer: [
						"const 变量：不可修改，编译期常量可用 constexpr",
						"const 指针（顶层）：int* const p，指针本身不可改",
						"指向 const 的指针（底层）：const int* p，所指对象不可改",
						"const 成员函数：不修改成员变量，可被 const 对象调用",
						"mutable 成员：const 成员函数中仍可修改",
					],
					difficulty: "easy",
					tags: ["语法"],
				},
				{
					id: "cpp-05",
					question: "static 关键字在 C++ 中的多种含义",
					hint: "局部静态、全局静态、类静态、静态成员函数",
					answer: [
						"局部静态变量：生命周期到程序结束，只初始化一次",
						"全局静态/文件内静态：内部链接，仅本文件可见",
						"类静态成员：属于类而非对象，所有实例共享一份",
						"静态成员函数：无 this 指针，只能访问静态成员",
						"面试常问：static 局部变量与全局变量的区别、线程安全（C++11 起局部静态初始化线程安全）",
					],
					difficulty: "easy",
					tags: ["语法"],
				},
				{
					id: "cpp-06",
					question: "STL 容器底层实现与复杂度（vector/list/map/unordered_map）",
					hint: "笔试常考，面试追问内存布局",
					answer: [
						"vector：动态数组，连续内存，随机访问 O(1)，尾部插入均摊 O(1)，中间插入 O(n)",
						"list：双向链表，非连续，任意位置插入 O(1)，随机访问 O(n)",
						"map：红黑树，有序，查找/插入 O(log n)",
						"unordered_map：哈希表，查找/插入均摊 O(1)，无序",
						"vector 扩容机制：倍增策略（通常 ×2），涉及拷贝/移动与迭代器失效",
					],
					difficulty: "medium",
					tags: ["STL", "数据结构"],
				},
				{
					id: "cpp-07",
					question: "内存模型：栈、堆、全局区、常量区、代码区",
					hint: "程序内存布局，new/delete 与栈上对象",
					answer: [
						"栈：函数局部变量，自动分配释放，容量小（默认 1-8MB），速度快",
						"堆：动态分配（new/malloc），手动管理，容量大",
						"全局/静态区：全局变量、静态变量、常量（部分实现）",
						"代码区：函数机器码，只读",
						"堆与栈的区别：分配方式、生命周期、大小、效率、碎片",
					],
					difficulty: "easy",
					tags: ["内存"],
				},
				{
					id: "cpp-08",
					question: "内存泄漏的检测与避免方法",
					hint: "游戏项目内存管理是重点",
					answer: [
						"成因：new 不 delete、失去指针、循环引用（shared_ptr）",
						"工具：Visual Studio 内存诊断、Valgrind、AddressSanitizer（ASan）",
						"UE5：LLM（Low Level Memory Tracker）统计各模块内存",
						"避免：RAII、智能指针、对象池、规范资源释放流程",
						"加分：重载 new/delete 记录分配点、快照对比定位泄漏",
					],
					difficulty: "medium",
					tags: ["内存", "工具"],
				},
				{
					id: "cpp-09",
					question:
						"构造函数和析构函数可以是虚函数吗？基类析构函数为什么必须声明为 virtual？",
					hint: "多态与对象生命周期的高频考点",
					answer: [
						"构造函数不能是虚函数：对象构造时 vptr 尚未建立，无法做动态绑定",
						"析构函数可以是虚函数，且基类析构函数必须声明为 virtual",
						"原因：通过基类指针 delete 派生类对象时，若析构非虚，只调用基类析构，派生类资源泄漏",
						"派生类析构会自动调用基类析构（无需显式调用）",
						"vtable 中析构函数条目是「析构函数 + 清理删除器」两个槽位",
					],
					difficulty: "medium",
					tags: ["多态", "生命周期"],
				},
				{
					id: "cpp-10",
					question: "C++ 内存对齐的规则与作用？给一个结构体算 sizeof",
					hint: "笔试计算题高频，面试追问原理",
					answer: [
						"对齐规则：每个成员的偏移量是其对齐数的整数倍；结构体总大小是最大对齐数的整数倍",
						"对齐数 = min(成员大小, 默认对齐数)，64 位下默认 8",
						"作用：CPU 按对齐地址访问内存更快，避免跨缓存行/页加载",
						"示例：struct { char a; int b; } → 8 字节（a 占 1，填充 3，b 占 4）",
						"可用 #pragma pack / alignas 修改对齐，游戏网络协议常用 pack(1) 避免填充",
					],
					difficulty: "medium",
					tags: ["内存", "笔试"],
				},
				{
					id: "cpp-11",
					question: "new 与 malloc 的区别？delete 与 free 呢？",
					hint: "C 与 C++ 内存分配的核心差异",
					answer: [
						"new 是运算符，malloc 是函数",
						"new 自动计算字节数并调用构造函数；malloc 只分配原始内存",
						"new 返回类型化指针（类型安全）；malloc 返回 void* 需强转",
						"delete 调用析构函数再释放；free 只释放内存",
						"new[]/delete[] 配对：数组版本会记录元素个数以便逐个析构",
					],
					difficulty: "easy",
					tags: ["内存"],
				},
			],
		},
		{
			id: "graphics",
			name: "图形学",
			description: "客户端面试区分度最高的考点",
			icon: "material-symbols:image",
			questions: [
				{
					id: "gr-01",
					question: "描述完整的渲染管线流程",
					hint: "从顶点到屏幕像素的每一步",
					answer: [
						"输入装配：顶点数据 → 顶点缓冲（VAO/VBO）",
						"顶点着色器：MVP 变换，世界/相机/投影空间",
						"几何着色器（可选）：图元处理、生成新顶点",
						"光栅化：图元 → 片元，插值顶点属性",
						"片元着色器：计算最终颜色（光照、纹理采样）",
						"测试与混合：深度测试、模板测试、颜色混合",
						"帧缓冲：写入屏幕或离屏渲染目标",
					],
					difficulty: "medium",
					tags: ["管线"],
				},
				{
					id: "gr-02",
					question: "MVP 矩阵：模型/视图/投影各自的作用",
					hint: "坐标空间变换链路",
					answer: [
						"Model：物体本地空间 → 世界空间（位移/旋转/缩放）",
						"View：世界空间 → 相机空间（以相机为原点）",
						"Projection：相机空间 → 裁剪空间（透视/正交）",
						"透视投影：近大远小，w 分量做透视除法",
						"完整链路：Object → World → View → Clip → NDC → Screen",
					],
					difficulty: "medium",
					tags: ["矩阵"],
				},
				{
					id: "gr-03",
					question: "冯氏光照模型与 Blinn-Phong 的区别",
					hint: "环境光/漫反射/镜面反射",
					answer: [
						"环境光 Ambient：全局常量近似间接光照",
						"漫反射 Diffuse：法线与光源方向点乘，与视角无关",
						"镜面反射 Specular：与视角有关，高光",
						"Phong 用反射向量与视角比较；Blinn-Phong 用半程向量（H = L+V 归一化）",
						"Blinn-Phong 更快且高光更柔和，是 Phong 的优化",
					],
					difficulty: "medium",
					tags: ["光照"],
					postSlug: "graphics-lighting-models",
				},
				{
					id: "gr-04",
					question: "深度缓冲（Z-Buffer）的工作原理",
					hint: "遮挡剔除的硬件基础",
					answer: [
						"为每个像素存储当前最小深度值",
						"光栅化时比较片元深度与缓冲值，通过则更新并写入颜色",
						"深度测试在片元着色器之后（Early-Z 除外）",
						"精度问题：近平面附近的精度损失（非线性深度）",
						"优化：Early-Z、深度预 pass、反向 Z",
					],
					difficulty: "easy",
					tags: ["光栅化"],
				},
				{
					id: "gr-05",
					question: "纹理映射与 mipmap 的作用",
					hint: "纹理采样、走样与性能",
					answer: [
						"纹理坐标 UV 映射到模型表面",
						"纹理过滤：最近邻/双线性/三线性",
						"mipmap：预生成逐级缩小一半的纹理链",
						"解决远处纹理闪烁（走样），同时提升缓存命中率",
						"各向异性过滤解决倾斜表面的模糊",
					],
					difficulty: "easy",
					tags: ["纹理"],
				},
				{
					id: "gr-06",
					question: "Draw Call 是什么？如何减少 Draw Call？",
					hint: "性能优化的核心概念，客户端必问",
					answer: [
						"Draw Call：CPU 向 GPU 提交一次绘制命令",
						"每次提交有固定开销（状态切换、命令缓冲），过多导致 CPU 瓶颈",
						"合批：把同材质网格合并成一次提交（Static Batching/Dynamic Batching）",
						"实例化渲染 Instancing：一次提交绘制多个实例（大量相同物体）",
						"纹理图集/材质合并减少状态切换；UE 的 Nanite 与合并 Actor",
					],
					difficulty: "medium",
					tags: ["性能"],
				},
				{
					id: "gr-07",
					question: "法线贴图（Normal Mapping）的原理",
					hint: "在不增加面数的情况下增加细节",
					answer: [
						"把高模法线烘焙到切线空间的法线贴图",
						"片元着色器采样法线，替代几何法线做光照计算",
						"切线空间（TBN 矩阵）保证法线在物体表面局部方向",
						"好处：低模获得高模光影细节，性能开销小",
						"局限：轮廓依然是低模，只能骗光照不能骗几何",
					],
					difficulty: "medium",
					tags: ["纹理", "光照"],
				},
				{
					id: "gr-08",
					question: "什么是渲染管线的 CPU/GPU 瓶颈？如何定位？",
					hint: "性能分析思路，体现工程能力",
					answer: [
						"CPU 瓶颈：Draw Call 过多、逻辑开销、资源加载阻塞",
						"GPU 瓶颈：像素过载（overdraw）、着色器复杂度、带宽",
						"定位工具：GPU Profiler（RenderDoc、PIX、Unreal Insights）",
						"帧耗时分解：CPU 帧时间 vs GPU 帧时间对比",
						"常见优化：LOD、遮挡剔除、减少 overdraw、合批、异步加载",
					],
					difficulty: "hard",
					tags: ["性能", "优化"],
				},
				{
					id: "gr-09",
					question: "前向渲染 vs 延迟渲染的区别、优缺点？各适合什么场景？",
					hint: "《鸣潮》等开放世界高频方案，图形学必考",
					answer: [
						"前向渲染：每个物体做完整光照计算，一次 pass；支持 MSAA、透明物体",
						"延迟渲染：几何 pass 写入 G-Buffer（法线/位置/颜色），光照 pass 屏幕空间计算",
						"延迟渲染优点：光源数量对开销影响小，适合大量动态光源",
						"延迟渲染缺点：G-Buffer 带宽/内存大，不支持 MSAA（需 TAA），透明物体需额外处理",
						"移动端常见方案：TBDR 架构下延迟渲染 + 前向混合，或 UE 的 Forward+（分块光照）",
					],
					difficulty: "hard",
					tags: ["渲染", "性能"],
				},
				{
					id: "gr-10",
					question:
						"Shadow Map 阴影映射原理？阴影失真（shadow acne）如何解决？",
					hint: "实时阴影的核心技术",
					answer: [
						"原理：先从光源视角渲染深度图（Shadow Map），渲染时比较片元深度与阴影图深度",
						"片元深度 > 阴影图深度 → 被遮挡，处于阴影中",
						"shadow acne（阴影痤疮/失真）：深度精度有限导致表面自阴影闪烁",
						"解决：深度偏移（Depth Bias）、法线偏移（Normal Bias）、斜率缩放偏移",
						"软阴影：PCF（多次采样）、PCSS（百分比近邻软阴影）、级联阴影（CSM）用于大场景",
					],
					difficulty: "hard",
					tags: ["阴影", "渲染"],
					postSlug: "graphics-shadows-aa",
				},
				{
					id: "gr-11",
					question: "MSAA / FXAA / TAA 抗锯齿的原理与区别",
					hint: "不同抗锯齿方案的取舍",
					answer: [
						"MSAA：多重采样，在子像素处计算覆盖率，边缘硬件级平滑；带宽开销大，延迟渲染不支持",
						"FXAA：后处理，检测边缘做模糊；快但会模糊纹理细节",
						"TAA：时间性抗锯齿，用历史帧样本+运动向量混合；质量高，但会引入鬼影（ghosting）",
						"UE 默认 TAA；移动端常用 FXAA 或 MSAA 4x",
						"TAA 与现代渲染结合好（延迟渲染、体积光），但需要运动向量缓冲",
					],
					difficulty: "hard",
					tags: ["抗锯齿", "渲染"],
					postSlug: "graphics-shadows-aa",
				},
			],
		},
		{
			id: "ue",
			name: "Unreal 引擎",
			description: "库洛鸣潮/战双均基于 UE，必考方向",
			icon: "material-symbols:videogame-asset",
			questions: [
				{
					id: "ue-01",
					question: "UObject / AActor / APawn / ACharacter 的区别与继承链",
					hint: "引擎对象模型的核心",
					answer: [
						"UObject：所有引擎对象的基类，提供反射（UCLASS/UPROPERTY）、GC、序列化",
						"AActor：可放入关卡的对象，有 Transform、可被 Spawn/Destroy，生命周期由关卡管理",
						"APawn：可被 Controller 控制的 Actor，可响应输入",
						"ACharacter：Pawn + 骨骼网格 + 胶囊体 + 移动组件，人形角色标准",
						"GC 机制：UObject 引用追踪 + 可达性分析，非 C++ 原生 new/delete",
					],
					difficulty: "medium",
					tags: ["对象模型"],
					postSlug: "ue5-character-class",
				},
				{
					id: "ue-02",
					question: "TICK 机制：Actor 与 Component 的 Tick 顺序",
					hint: "帧循环与执行顺序",
					answer: [
						"引擎主循环：Tick 前更新 → Actor Tick → Tick 后更新 → 渲染",
						"Actor Tick 默认调用其所有 Component 的 Tick（先 Component 后 Actor）",
						"可通过 TickGroup 控制顺序：PrePhysics/DuringPhysics/PostPhysics",
						"大量 Actor 时禁用不需要的 Tick（SetActorTickEnabled(false)）",
						"性能：Tick 开销与 Actor 数量线性相关，常配合 帧率优化",
					],
					difficulty: "medium",
					tags: ["帧循环"],
				},
				{
					id: "ue-03",
					question: "蓝图与 C++ 如何选择？通信方式有哪些？",
					hint: "工程协作与架构设计",
					answer: [
						"C++：性能关键、核心逻辑、框架层；蓝图：快速迭代、表现层、策划使用",
						"通信：BlueprintCallable（C++ 暴露给蓝图）、BlueprintImplementableEvent（蓝图实现 C++ 调用）",
						"反射宏：UPROPERTY(BlueprintReadWrite)、UFUNCTION(BlueprintCallable)",
						"事件委托：动态委托可在蓝图绑定，接口 UInterface",
						"工程实践：C++ 定框架，蓝图做表现，避免大型逻辑全放蓝图",
					],
					difficulty: "medium",
					tags: ["架构"],
				},
				{
					id: "ue-04",
					question: "GAS（Gameplay Ability System）核心类及关系",
					hint: "大型项目技能系统事实标准",
					answer: [
						"UAbilitySystemComponent（ASC）：技能系统挂载点，协调所有组件",
						"UGameplayAbility：单个技能定义，可授予/激活/取消/冷却",
						"UGameplayEffect（GE）：属性修改器（伤害/治疗/Buff），不直接改属性",
						"UAttributeSet：属性集合（生命/法力/攻击等），属性变化回调",
						"数据流：GA 激活 → 应用 GE → GE 修改 AttributeSet → 广播变化",
					],
					difficulty: "hard",
					tags: ["GAS", "技能"],
					postSlug: "ue5-gas-ability-system",
				},
				{
					id: "ue-05",
					question: "Animation Blueprint 状态机与 BlendSpace",
					hint: "动画系统基础",
					answer: [
						"AnimGraph：状态机（State Machine）驱动动画播放",
						"状态切换条件：速度、是否落地等变量",
						"BlendSpace：按参数（如速度方向）混合多个动画，实现平滑过渡",
						"C++ 通过 UAnimInstance 子类暴露变量（NativeUpdateAnimation 每帧更新）",
						"Montage：片段式动画播放，适合攻击/受击等一次性动作",
					],
					difficulty: "medium",
					tags: ["动画"],
					postSlug: "ue5-montage-metasound",
				},
				{
					id: "ue-06",
					question: "CharacterMovementComponent 的移动流程",
					hint: "引擎源码级理解，面试加分项",
					answer: [
						"AddMovementInput 累积输入向量（缓冲）",
						"TickComponent → ConsumeInputVector 取出输入",
						"ControlledCharacterMove → PerformMovement 总调度",
						"物理子步骤：PhysWalking/PhysFalling 等，处理碰撞与地面检测",
						"八个阶段：Snapshot → 外力累积 → 加速度 → 仲裁 → 物理模拟 → 旋转 → 平台跟随 → 广播",
					],
					difficulty: "hard",
					tags: ["移动", "源码"],
					postSlug: "ue5-character-class",
				},
				{
					id: "ue-07",
					question: "反射机制：UPROPERTY / UFUNCTION 宏如何工作",
					hint: "UE 的 C++ 扩展核心",
					answer: [
						"UHT（Unreal Header Tool）在编译前解析宏，生成 .generated.h 反射代码",
						"运行时通过反射查询属性/调用函数/序列化",
						"UPROPERTY 控制：序列化、蓝图可见性、GC 引用追踪",
						"UFUNCTION：蓝图可调用、网络复制、事件",
						"作用：编辑器属性面板、蓝图互操作、GC、网络同步",
					],
					difficulty: "hard",
					tags: ["反射"],
				},
				{
					id: "ue-08",
					question: "垃圾回收（GC）在 UE 中如何工作？与 C++ 原生内存管理区别",
					hint: "对象生命周期管理",
					answer: [
						"UObject 由 GC 管理，使用可达性分析（标记-清除）",
						"UPROPERTY() 声明的引用被 GC 追踪，非 UPROPERTY 裸指针不受保护",
						"GC 触发时机：内存压力/手动 ForceGarbageCollection",
						"AddToRoot 防止被回收；IsValid 检查对象有效性",
						"非 UObject（纯 C++ 对象）走原生 RAII，需手动管理",
					],
					difficulty: "hard",
					tags: ["内存", "GC"],
				},
				{
					id: "ue-09",
					question:
						"GameMode / GameState / PlayerController / Pawn / PlayerState 的分工？",
					hint: "UE Gameplay 框架核心，必考",
					answer: [
						"GameMode：仅服务器，定义游戏规则（胜利条件、生成规则），每局一个",
						"GameState：同步给所有客户端的全局状态（比分、游戏阶段）",
						"PlayerController：玩家的输入与控制中枢，常驻（死亡后仍存在）",
						"Pawn：可被控制的实体（角色/载具），PlayerController Possess 后接管",
						"PlayerState：每个玩家的同步状态（分数、名字），跨回合保留",
					],
					difficulty: "medium",
					tags: ["Gameplay", "框架"],
					postSlug: "ue5-gameplay-framework",
				},
				{
					id: "ue-10",
					question: "UE 网络同步：Replication / RPC 原理？帧同步 vs 状态同步？",
					hint: "多人游戏核心概念，客户端岗加分项",
					answer: [
						"Replication：服务器权威，属性标记 Replicated 自动同步到客户端",
						"RPC：Server RPC（客户端→服务器，受信任校验）、Multicast RPC（广播）、Client RPC",
						"状态同步：同步最终状态（位置、血量），客户端插值补间；实现简单、容错好",
						"帧同步：同步输入指令，各端确定性模拟（格斗/RTS 常用）；流量小但要求确定性",
						"UE 默认状态同步 + 角色移动预测（Client Prediction）+ 纠偏（Correction）",
					],
					difficulty: "hard",
					tags: ["网络"],
					postSlug: "ue5-network-replication",
				},
				{
					id: "ue-11",
					question: "UE 资源加载：硬引用 vs 软引用？异步加载怎么做？",
					hint: "大型游戏资源管理核心，性能关键",
					answer: [
						"硬引用：直接 UPROPERTY 引用资产，加载父资产时同步加载；简单但可能加载过多",
						"软引用：TSoftObjectPtr/TSoftClassPtr，只存路径不加载，需显式加载",
						"异步加载：FStreamableManager::RequestAsyncLoad、UAssetManager、LoadPackageAsync",
						"用途：关卡流送（Level Streaming）、按需加载技能/怪物、避免启动卡顿",
						"引用链陷阱：硬引用会拖拽整个依赖图，导致内存膨胀",
					],
					difficulty: "hard",
					tags: ["资源", "性能"],
					postSlug: "ue5-asset-loading",
				},
				{
					id: "ue-12",
					question: "UE 多线程模型：游戏线程 / 渲染线程 / RHI 线程分工？",
					hint: "引擎并行架构理解，深入面试加分",
					answer: [
						"GameThread：游戏逻辑、蓝图、物理（部分），每帧驱动主循环",
						"RenderThread：渲染命令构建（场景图遍历、剔除、生成渲染命令）",
						"RHI 线程：把渲染命令提交给 GPU 驱动",
						"渲染命令通过命令队列（Command List）异步传递，避免阻塞",
						"调试：stat unit 查看各线程耗时；FRunnable 自定义工作线程；TaskGraph 并行任务",
					],
					difficulty: "hard",
					tags: ["多线程", "架构"],
				},
			],
		},
		{
			id: "algo",
			name: "算法",
			description: "笔试主力题型，面试也会手写代码",
			icon: "material-symbols:functions",
			questions: [
				{
					id: "al-01",
					question: "手写快速排序，并分析复杂度",
					hint: "高频手写题，注意退化情况",
					answer: [
						"分治：选 pivot → 分区 → 递归左右",
						"平均 O(n log n)，最坏 O(n²)（有序数组 + 固定 pivot）",
						"优化：随机 pivot、三数取中、小数组插排",
						"不稳定排序，原地实现（额外空间 O(log n) 递归栈）",
					],
					difficulty: "medium",
					tags: ["排序"],
					postSlug: "algorithm-handwriting-templates",
				},
				{
					id: "al-02",
					question: "二叉树前/中/后序遍历：递归与迭代写法",
					hint: "必须能熟练手写迭代版",
					answer: [
						"递归：访问根 → 左 → 右（前序）等，代码简单",
						"前序迭代：栈，先压右子再压左子",
						"中序迭代：一路向左入栈，弹出访问后转向右子树",
						"后序迭代：双栈或记录上次访问节点",
						"复杂度：时间 O(n)，空间 O(h)（h 为树高）",
					],
					difficulty: "medium",
					tags: ["树"],
					postSlug: "algorithm-handwriting-templates",
				},
				{
					id: "al-03",
					question: "DFS 与 BFS 的区别与适用场景",
					hint: "图搜索两大基础",
					answer: [
						"DFS：栈/递归，一条路走到底，空间 O(深度)",
						"BFS：队列，逐层扩展，空间 O(宽度)，适合最短路",
						"DFS 适合：连通性、回溯、拓扑排序（后序）",
						"BFS 适合：无权图最短路、层序遍历",
						"复杂度均为 O(V+E)（图）",
					],
					difficulty: "easy",
					tags: ["图", "搜索"],
				},
				{
					id: "al-04",
					question: "链表反转（迭代与递归）",
					hint: "高频手写题",
					answer: [
						"迭代：三指针 prev/curr/next，逐个翻转指向",
						"递归：先反转剩余，再让 head->next->next = head",
						"注意：处理空链表与单节点，返回新头节点",
						"变体：区间反转（92 题）、K 个一组反转（25 题）",
					],
					difficulty: "easy",
					tags: ["链表"],
					postSlug: "algorithm-handwriting-templates",
				},
				{
					id: "al-05",
					question: "动态规划：以「最长递增子序列」为例讲思路",
					hint: "DP 状态定义与转移方程",
					answer: [
						"定义 dp[i] = 以 nums[i] 结尾的 LIS 长度",
						"转移：dp[i] = max(dp[j] + 1)，j < i 且 nums[j] < nums[i]",
						"答案：max(dp)，O(n²)",
						"优化：贪心 + 二分（维护 tails 数组）O(n log n)",
						"DP 三步：状态定义 → 转移方程 → 初始化/边界",
					],
					difficulty: "hard",
					tags: ["DP"],
				},
				{
					id: "al-06",
					question: "哈希表解决冲突的方法",
					hint: "数据结构基础",
					answer: [
						"开放寻址法：线性探测/二次探测/双重散列",
						"链地址法：桶内挂链表（C++ unordered_map 常用）",
						"再散列：扩容时重新计算哈希",
						"负载因子：冲突概率与扩容时机",
						"STL unordered_map 用链地址 + 扩容（bucket 数倍增）",
					],
					difficulty: "medium",
					tags: ["哈希"],
				},
				{
					id: "al-07",
					question: "栈与队列：如何用两个栈实现队列",
					hint: "经典面试题",
					answer: [
						"push：压入 stack1",
						"pop：若 stack2 空，把 stack1 全部倒入 stack2，再 pop stack2 顶",
						"amortized O(1)：每个元素至多进出两次",
						"变体：两个队列实现栈（push 到非空队列，pop 时转移）",
					],
					difficulty: "easy",
					tags: ["栈", "队列"],
				},
				{
					id: "al-08",
					question: "二分查找的边界处理（左闭右开 vs 左闭右闭）",
					hint: "手写题的常见失分点",
					answer: [
						"左闭右闭 [l, r]：while (l <= r)，更新 l = mid+1 / r = mid-1",
						"左闭右开 [l, r)：while (l < r)，更新 l = mid+1 / r = mid",
						"统一写法后套模板，避免死循环",
						"变体：找第一个/最后一个等于 target 的位置",
						"注意 mid 计算防溢出：l + (r - l) / 2",
					],
					difficulty: "medium",
					tags: ["二分"],
				},
				{
					id: "al-09",
					question: "手写 LRU 缓存（双向链表 + 哈希表）",
					hint: "笔试高频手撕题，注意 O(1) 复杂度",
					answer: [
						"数据结构：哈希表（O(1) 定位）+ 双向链表（O(1) 移除/移动）",
						"get：命中则移到链表头部，未命中返回 -1",
						"put：已存在则更新并移到头部；不存在则插入头部，超出容量移除尾部",
						"为什么不用单向链表：删除尾部节点需要前驱指针，双向链表才能 O(1)",
						"复杂度：get/put 均 O(1)；注意边界（容量 0、重复 key）",
					],
					difficulty: "hard",
					tags: ["设计", "手撕"],
					postSlug: "algorithm-handwriting-templates",
				},
				{
					id: "al-10",
					question: "TopK 问题：堆 vs 快速选择的思路与复杂度",
					hint: "海量数据高频题",
					answer: [
						"堆方案：维护大小为 K 的小顶堆，遍历数据，大于堆顶则替换；O(n log K)",
						"快速选择：基于快排分区，只递归包含第 K 大的一侧；平均 O(n)，最坏 O(n²)",
						"TopK 最小用大顶堆，TopK 最大用小顶堆",
						"海量数据场景（内存放不下）：分治 + 哈希分桶，或外部排序",
						"堆方案可流式处理，快速选择需要全量数据",
					],
					difficulty: "medium",
					tags: ["堆", "排序"],
					postSlug: "algorithm-handwriting-templates",
				},
			],
		},
		{
			id: "os",
			name: "计算机基础",
			description: "操作系统/网络/编译原理基础",
			icon: "material-symbols:memory",
			questions: [
				{
					id: "os-01",
					question: "进程与线程的区别，为什么游戏多用多线程",
					hint: "资源隔离、共享、切换开销",
					answer: [
						"进程：资源分配单位，独立地址空间，隔离性强",
						"线程：CPU 调度单位，共享进程地址空间，切换开销小",
						"游戏：渲染线程/游戏逻辑线程/音频线程分工",
						"游戏多线程挑战：数据竞争、帧同步、死锁",
						"UE5：GameThread/RenderThread/RHI 线程分工",
					],
					difficulty: "easy",
					tags: ["OS"],
					postSlug: "cs-os-multithreading",
				},
				{
					id: "os-02",
					question: "死锁产生的四个必要条件",
					hint: "操作系统经典考点",
					answer: [
						"互斥：资源一次只能被一个进程占用",
						"持有并等待：持有资源同时等待其他资源",
						"不可剥夺：资源不能被强行抢占",
						"循环等待：进程间形成环形等待链",
						"预防：破坏任一条件；银行家算法避免死锁",
					],
					difficulty: "easy",
					tags: ["OS"],
				},
				{
					id: "os-03",
					question: "TCP 三次握手与四次挥手",
					hint: "网络基础必考",
					answer: [
						"三次握手：SYN → SYN+ACK → ACK，确认双方收发能力",
						"为什么三次：防止失效连接请求到达导致资源浪费",
						"四次挥手：FIN → ACK → FIN → ACK，半关闭状态",
						"TIME_WAIT：主动关闭方等待 2MSL，确保最后一个 ACK 到达",
						"游戏网络常用 UDP（低延迟可丢包）+ 自定义可靠层",
					],
					difficulty: "easy",
					tags: ["网络"],
				},
				{
					id: "os-04",
					question: "虚拟内存与分页机制",
					hint: "OS 核心概念",
					answer: [
						"虚拟内存：进程拥有连续虚拟地址空间，按需映射物理内存",
						"分页：虚拟页 → 物理帧，页表记录映射",
						"缺页中断：访问未映射页时触发，从磁盘换入",
						"好处：隔离、超内存运行、共享库",
						"游戏相关：内存对齐、Cache 友好性影响性能",
					],
					difficulty: "medium",
					tags: ["OS", "内存"],
					postSlug: "cs-os-multithreading",
				},
				{
					id: "os-05",
					question: "进程间通信方式（IPC）",
					hint: "面试常问列举",
					answer: [
						"管道（匿名/命名）：单向字节流",
						"消息队列：内核消息缓冲",
						"共享内存：最快，需同步机制配合",
						"信号量：同步与互斥",
						"Socket：跨主机通信",
					],
					difficulty: "easy",
					tags: ["OS"],
				},
				{
					id: "os-06",
					question: "什么是缓存一致性/伪共享？游戏编程如何避免？",
					hint: "多线程性能高级题",
					answer: [
						"CPU 多级缓存，缓存行（通常 64 字节）为同步单位",
						"伪共享：不同线程修改同一缓存行内不同变量，导致缓存行反复失效",
						"避免：变量填充 padding 到独立缓存行、按线程分区数据",
						"游戏案例：多线程任务系统、每线程独立内存池",
						"加分：cacheline 对齐（alignas(64)）",
					],
					difficulty: "hard",
					tags: ["性能", "多线程"],
					postSlug: "cs-os-multithreading",
				},
				{
					id: "os-07",
					question: "内存池/对象池的原理？为什么游戏开发中大量使用？",
					hint: "游戏性能优化核心考点",
					answer: [
						"对象池：预分配一批对象，用后归还复用，避免频繁构造/析构",
						"内存池：预分配大块内存按固定大小切块管理，避免频繁 malloc/free",
						"好处：避免内存碎片、减少系统调用开销、提升缓存局部性",
						"游戏场景：子弹/特效/伤害数字等高频创建销毁对象",
						"UE：对象池（Actor Pool）、引擎级 allocator；注意池满策略与对象状态重置",
					],
					difficulty: "medium",
					tags: ["性能", "内存"],
					postSlug: "cs-os-multithreading",
				},
				{
					id: "os-08",
					question:
						"互斥锁 vs 自旋锁 vs 原子操作 vs 条件变量，什么场景用哪个？",
					hint: "多线程同步方案选择",
					answer: [
						"互斥锁（mutex）：临界区较长时用，阻塞让出 CPU；有系统调用开销",
						"自旋锁（spinlock）：临界区极短时用，忙等不切换线程；会浪费 CPU",
						"原子操作：单变量计数/标志用 CAS/原子加减，无锁最快",
						"条件变量：等待某个条件满足（生产者-消费者），配合互斥锁",
						"游戏场景：任务队列用互斥+条件变量；引用计数用原子；极短共享标志用自旋",
					],
					difficulty: "medium",
					tags: ["多线程"],
					postSlug: "cs-os-multithreading",
				},
				{
					id: "os-09",
					question: "进程与线程的区别？线程间共享什么、独享什么？",
					hint: "操作系统基础必考",
					answer: [
						"进程：资源分配的最小单位，独立地址空间，隔离性强",
						"线程：CPU 调度的最小单位，共享进程地址空间",
						"线程共享：代码段、数据段、堆、打开的文件、信号",
						"线程独享：栈、寄存器、线程局部存储（TLS）",
						"切换开销：线程 < 进程；进程间通信需 IPC，线程间直接共享内存",
					],
					difficulty: "easy",
					tags: ["OS"],
				},
				{
					id: "os-10",
					question: "虚拟内存与分页机制？页面置换算法？",
					hint: "OS 核心概念延伸",
					answer: [
						"虚拟内存：进程拥有连续虚拟地址空间，按需映射物理内存",
						"分页：虚拟页 → 物理帧，页表记录映射",
						"缺页中断：访问未映射页时触发，从磁盘换入",
						"置换算法：FIFO（可能抖动）、LRU（最优近似）、时钟算法（CLOCK）",
						"游戏相关：内存映射文件、按需加载资源",
					],
					difficulty: "medium",
					tags: ["OS", "内存"],
				},
			],
		},
		{
			id: "game",
			name: "游戏开发常识",
			description: "行业认知与项目经验考察",
			icon: "material-symbols:sports-esports",
			questions: [
				{
					id: "gd-01",
					question: "说说你玩过的游戏里，哪个系统的实现让你印象深刻",
					hint: "展示行业认知与思考深度",
					answer: [
						"选一个具体系统：战斗手感、开放世界加载、渲染效果",
						"拆解：它做了什么 → 大概怎么实现 → 为什么好",
						"联系自己学过的技术：3C、GAS、LOD 等",
						"结合库洛游戏：鸣潮的战斗手感/战双的打击感",
						"加分：提出「如果我来做会怎么优化」",
					],
					difficulty: "medium",
					tags: ["认知"],
				},
				{
					id: "gd-02",
					question: "为什么想进游戏行业/想做客户端？",
					hint: "HR 面高频，也是技术面开场",
					answer: [
						"真诚的动机：热爱游戏 + 技术兴趣，避免空洞的「喜欢游戏」",
						"结合经历：从什么开始接触引擎/写代码",
						"技术视角：为什么选客户端（渲染/性能/交互反馈直接可见）",
						"说明自己的投入：博客、Demo、学习过程",
					],
					difficulty: "easy",
					tags: ["动机"],
				},
				{
					id: "gd-03",
					question: "如何看待加班与游戏行业的工作强度",
					hint: "行业现实，坦诚回答",
					answer: [
						"理解行业特点：版本节奏、上线压力",
						"表达意愿：对技术有热情，接受高强度周期",
						"同时说明效率意识：好的工程实践减少无效加班",
						"避免两种极端：过度抱怨 or 无脑接受",
					],
					difficulty: "easy",
					tags: ["心态"],
				},
				{
					id: "gd-04",
					question: "你做过的最有挑战的技术问题是什么？怎么解决的？",
					hint: "STAR 法则讲故事",
					answer: [
						"S 情境：项目背景与目标",
						"T 任务：我负责的具体任务",
						"A 行动：技术方案、踩坑过程、如何定位（工具/日志/二分）",
						"R 结果：量化结果（性能提升、功能完成）",
						"加分：总结方法论（如「以后遇到 X 会先查 Y」）",
					],
					difficulty: "medium",
					tags: ["项目"],
				},
				{
					id: "gd-05",
					question: "游戏主循环（Game Loop）的组成？固定时间步长解决什么问题？",
					hint: "游戏开发基础原理",
					answer: [
						"主循环：处理输入 → 更新逻辑（Update）→ 渲染（Render）→ 循环",
						"帧率不稳定时，物理/逻辑若按帧执行会出现速度不一致（帧率依赖）",
						"固定时间步长：逻辑按固定 dt 累加执行（如 60Hz），渲染插值补间",
						"UE：默认可变步长 + 物理固定步长（1/60s，可配置）",
						"好处：确定性、帧率无关、网络同步的基础",
					],
					difficulty: "medium",
					tags: ["原理"],
				},
				{
					id: "gd-06",
					question: "为什么连续内存（数组）比链表遍历更快？",
					hint: "缓存局部性，游戏性能高频考点",
					answer: [
						"数组元素连续存放，CPU 加载一个缓存行（64B）可覆盖多个元素",
						"链表节点分散，每次访问都可能缓存未命中，需从内存重新加载",
						"顺序访问有很好的空间局部性和时间局部性，硬件预取器可加速",
						"游戏场景：组件数组（ECS）、对象池、紧凑的顶点缓冲",
						"结论：内存布局对性能影响巨大，数据导向设计（DOD）思想",
					],
					difficulty: "medium",
					tags: ["性能", "缓存"],
				},
				{
					id: "gd-07",
					question:
						"了解《鸣潮》/《战双帕弥什》吗？如果是你，会怎么优化其中某个系统？",
					hint: "考察对公司的了解与思考深度",
					answer: [
						"展示对游戏的实际了解：战斗手感、开放世界、渲染风格",
						"选一个具体系统分析：如开放世界加载（LOD/流送）、战斗打击感（动画/受击反馈）",
						"结合技术方案：帧同步/状态同步、移动端性能优化（TBDR、合批）",
						"提出可讨论的优化方向，体现工程思维而非空谈",
						"诚实：不了解就说「我玩过/看过，具体实现我会从 X 入手分析」",
					],
					difficulty: "medium",
					tags: ["认知", "公司"],
				},
				{
					id: "gd-08",
					question: "游戏开发中遇到最难排查的 Bug 是怎么定位的？",
					hint: "考察调试能力与工程方法论",
					answer: [
						"现象描述：复现路径、出现频率、环境差异",
						"二分定位：注释/隔离代码块、Git 历史回溯（git bisect）",
						"工具：调试器（断点/内存查看）、日志、性能分析器",
						"UE 专用：Unreal Insights、日志分类、ensure/check、崩溃日志栈",
						"典型故事：内存越界（随数据量变化）、时序问题（偶发）、多线程竞态",
					],
					difficulty: "medium",
					tags: ["调试", "项目"],
				},
			],
		},
	],
};
